# Generated by Django 5.0.6 on 2024-06-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('investigating', 'Investigating'), ('fixed', 'Fixed'), ('cannotfix', 'CannotFix')], default='open', max_length=50),
        ),
    ]
