# Generated by Django 5.0.6 on 2024-06-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_hiringrequest_supportquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportquery',
            name='user',
        ),
    ]
