# Generated by Django 5.0.6 on 2024-06-07 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_user_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewedby',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewedissue', to='Tracker.issue'),
        ),
        migrations.AlterField(
            model_name='viewedby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vieweduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
