# Generated by Django 5.0.6 on 2024-06-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='companyuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
