# Generated by Django 5.0.6 on 2024-06-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_alter_viewedby_issue_alter_viewedby_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='C:/Users/Asus/OneDrive/Desktop/Empty-image.jpg', upload_to='images'),
        ),
    ]
