# Generated by Django 5.0.6 on 2024-06-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_rename_description_feedback_comment_feedback_bool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='disabled',
        ),
    ]
