# Generated by Django 5.0.6 on 2024-06-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/images/Empty-image.jpg', upload_to='images'),
        ),
    ]
